# Generated by Django 3.2.23 on 2023-12-23 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Факультет',
                'verbose_name_plural': 'Факультеты',
            },
        ),
        migrations.CreateModel(
            name='entrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='ФИО')),
                ('group', models.PositiveSmallIntegerField(default=0, verbose_name='Группа')),
                ('flow', models.PositiveSmallIntegerField(default=0, verbose_name='Поток')),
                ('exam_list', models.PositiveIntegerField(default=0, verbose_name='Номер экзаменационного листа')),
                ('department_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.department')),
                ('faculty_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.faculty')),
            ],
            options={
                'verbose_name': 'Абитуриент',
                'verbose_name_plural': 'Абитуриенты',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.faculty'),
        ),
    ]
