# Generated by Django 3.2.23 on 2023-12-23 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20231223_1907'),
    ]

    operations = [
        migrations.CreateModel(
            name='exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.PositiveSmallIntegerField(default=0, verbose_name='Поток')),
                ('classroom', models.PositiveSmallIntegerField(default=0, verbose_name='Аудитория')),
                ('exam_date', models.DateTimeField(verbose_name='Дата экзамена')),
                ('consult_date', models.DateTimeField(verbose_name='Дата консультации')),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
        ),
        migrations.AlterField(
            model_name='entrant',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.department', verbose_name='ID кафедры'),
        ),
        migrations.CreateModel(
            name='mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.PositiveSmallIntegerField(default=0, verbose_name='Оценка')),
                ('entrant_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.entrant', verbose_name='ID Абитуриента')),
                ('exam_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.exam', verbose_name='ID экзамена')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='subject_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.subject', verbose_name='ID предмета'),
        ),
    ]
