# Generated by Django 3.2.23 on 2023-12-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20231223_1926'),
    ]

    operations = [
        migrations.CreateModel(
            name='flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow_num', models.PositiveIntegerField(verbose_name='Номер потока')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
            },
        ),
        migrations.RemoveField(
            model_name='exam',
            name='flow',
        ),
        migrations.CreateModel(
            name='group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_num', models.PositiveIntegerField(verbose_name='Номер группы')),
                ('flow_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.flow', verbose_name='Поток')),
            ],
            options={
                'verbose_name': 'Группа',
                'verbose_name_plural': 'Группы',
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.flow', verbose_name='Поток'),
        ),
    ]
