# Generated by Django 3.2.23 on 2023-12-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20231223_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrant',
            name='flow',
        ),
        migrations.RemoveField(
            model_name='entrant',
            name='group',
        ),
        migrations.AddField(
            model_name='entrant',
            name='flow_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.flow', verbose_name='Поток'),
        ),
        migrations.AddField(
            model_name='entrant',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='main.group', verbose_name='Группа'),
        ),
    ]
